version: "3.9"
services:
  web:
    container_name: "ext_auth_proxy"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
      PORT: 3000
      EXTENSION_ID: ""
      BASE_URL: "http://localhost:3000"
      LOGOUT_REDIRECT: "/"
      INDEX_REDIRECT: "https://acme.com"
      SITE_TITLE: "ACME"
      AUTH0_CLIENT_ID: ""
      AUTH0_BASE_URL: "https://ACME.us.auth0.com"
      AUTH0_CLIENT_SECRET: ""
      AUTH_SECRET: ""
      AUTH0_AUDIENCE: "https://api.ACME.com/"
